#!/bin/sh
#
# Fetch DVB scan files
#

# Arguments
DIR=$1
[ -z "$DIR" ] && DIR=$(dirname "$0")/../data/dvb-scan

# Update
if [ -d "${DIR}/.git" ]; then
  LAST=$(pwd)
  cd "${DIR}" || exit 1
  git fetch > /dev/null 2>&1 || exit 1
  git reset --hard > /dev/null 2>&1 || exit 1
  git pull > /dev/null 2>&1 || exit 1
  cd "${LAST}" || exit 1
# Fetch
elif [ ! -d "${DIR}" ]; then
  URL=https://github.com/tvheadend/dtv-scan-tables.git
  BRANCH=tvheadend
  git clone -b $BRANCH $URL "${DIR}" > /dev/null 2>&1 || exit 1
fi

mkdir -p "${DIR}/isdb-s"
cp $(dirname "$0")/../data/isdb-mux/BSAT-3a-110.0E "${DIR}/isdb-s/"
cp $(dirname "$0")/../data/isdb-mux/jp-* "${DIR}/isdb-t/"

# Note: will not update existing set (if not .git)
exit 0
